#!/bin/bash

# Identifiy the default gateway in the routing table

# Netstat combined with the -r option will display the
# kernel routing tables. This is commonly used with the -n option,
# which will only show numerical addresses rather than performing any
# sort of name resolution.

netstat -nr | grep 'default' | awk '{print $2}'