#!/bin/bash

# Identify the IP address of the DNS that
# responds to the following url: slash16.org
# DNS (англ. Domain Name System «система доменных имён»)

nslookup slash16.org | grep Server | awk '{print $2}'

# The first line contains the IP address of the DNS that responded.