#!/bin/bash

#Name the command that determines the state of the SSH service.

#Secure Shell (SSH) is a cryptographic network protocol for
#operating network services securely over an unsecured network.

service ssh status